project:
  type: website
  output-dir: docs

website:
  title: "Jannelle Navales"
  navbar:
    right:
      - about.qmd
      - text: Information Management
        menu: 
          - text: "IM Assignment 1"
            href: EPPS6354Assignment1.pdf
          - text: "IM Assignment 2"
            href: EPPS6354Assignment2.pdf
          - text: "IM Assignment 3"
            href: EPPS6354Assignment3.pdf
          - text: "IM Assignment 4"
            href: EPPS6354A4.pdf
          - text: "IM Assignment 5"
            href: EPPS6354A5.pdf
          - text: "IM Assignment 6"
            href: EPPS6354A6.pdf
          - text: "Proposal"
            href: EPPS6354Proposal.pdf
          - text: "Final Project Presentation"
            href: EPPS6354PresentationFinal.pdf
          - text: "Final Project Application"
            href: utdfmp.qmd
      - icon: github
        href: https://github.com/jannellenavales
      - icon: linkedin
        href: https://www.linkedin.com/jannelle-navales/
format:
  html:
    theme: united
    css: styles.css

editor: visual

