project:
  type: website
  output-dir: docs

website:
  title: "Jannelle Navales"
  navbar:
    right:
      - about.qmd
      - text: Information Management
        menu: 
          - text: "IM Assignment 1"
            href: imassignment1.qmd
          - text: "IM Assignment 2"
            href: imassignment2.qmd  
      - icon: github
        href: https://github.com/jannellenavales
      - icon: linkedin
        href: https://www.linkedin.com/jannelle-navales/
format:
  html:
    theme: united
    css: styles.css

editor: visual

