---
title: "Assignment 5"
author: "Jannelle Navales"
date: "2023-10-11"
categories: [r graphics, ggplot2, exporting]
---

**Plotting Without Packages**

```{r}

data(Seatbelts)
seatbelt <- data.frame (Year=floor(time(Seatbelts)) ,
Month=factor(cycle(Seatbelts) ,
labels=month.abb) , Seatbelts)
# floor() returns largest integer smaller or equal
# time looks for execution time? establishes time series
# cycle just repeats it?
# month.abb means three letter abbreviation for English months
str(seatbelt)
#factors -> categorical variables - fixed, known set - think month - correlated number
head(seatbelt)

#Create a histogram
# Random data
Y <- rnorm(50)
# Make sure no Y exceed [-3.5, 3.5]
Y[Y < -3.5 | Y > 3.5] <- NA # Selection/set range
x <- seq(-3.5, 3.5, .1)
dn <- dnorm(x)
par(mar=c(4.5, 4.1, 3.1, 0))
hist(Y, breaks=seq(-3.5, 3.5), ylim=c(0, 0.5), 
     col="gray80", freq=FALSE)
lines(x, dnorm(x), lwd=2)
par(mar=c(5.1, 4.1, 4.1, 2.1))

Y <- seatbelt$PetrolPrice
dn <- dnorm(x)
hist(Y) #simple
hist(Y,col="steelblue")
lines(density(seatbelt$PetrolPrice),lwd =2, col = 'black')

#Create a Scatterplot
x <-seatbelt$front
y <-seatbelt$rear
par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

#HorizontalBarChart
seatbelt$decade <- 10 * (seatbelt$Year %/% 10)
fatalitiesbydecade <- table(seatbelt$decade)
barplot(fatalitiesbydecade, 
        main = "Deaths by Decade",
        xlab = "Decade",
        ylab = "Number of Deaths",
        col = "darkolivegreen4",
        horiz=TRUE)

#VerticalBarChart

deaths_by_year <- tapply(seatbelt$DriversKilled, seatbelt$Year, sum)

barplot(deaths_by_year,
        main = "Total Deaths by Year",
        xlab = "Year",
        ylab = "Total Deaths",
        col = "darkolivegreen4",
        names.arg = unique(seatbelt$Year),
        ylim = c(0, max(deaths_by_year) + 20)) 

#BoxPlot
boxplot(seatbelt$DriversKilled,
        main = "Boxplot of Drivers Killed",
        ylab = "Deaths",
        col = "darkorange3",
        border = "black")

#PieChart - mtcars 
#note to self - take note of which datsets are appropriate for different forms of graphs in the future

data(mtcars)

# Create a pie chart showing the distribution of cylinder counts
data(mtcars)
View(mtcars)
cylinder_counts <- table(mtcars$cyl)
par(mar=c(0, 2, 1, 2), xpd=FALSE, cex=0.5)
pie(cylinder_counts, 
    labels = names(cylinder_counts), 
    main = "How Many Cylinders?", col = gray(seq(0.3,1.0,length=6)))

```

**Plotting With GGPlot**

```{r}
library(tidyverse)
data(Seatbelts)
seatbelt <- data.frame (Year=floor(time(Seatbelts)) ,
Month=factor(cycle(Seatbelts) ,
labels=month.abb) , Seatbelts)
# floor() returns largest integer smaller or equal
# time looks for execution time? establishes time series
# cycle just repeats it?
# month.abb means three letter abbreviation for English months
View(seatbelt)
str(seatbelt)
#factors -> categorical variables - fixed, known set - think month - correlated number
head(seatbelt)

#Create a histogram - original
# Y <- seatbelt$PetrolPrice
# dn <- dnorm(x)
# hist(Y) #simple
# hist(Y,col="steelblue")
# lines(density(seatbelt$PetrolPrice),lwd =2, col = 'black')

Y <- seatbelt$PetrolPrice
ggplot(data = data.frame(Y = Y), aes(x = Y)) +
  geom_histogram(color = 'black', fill = 'steelblue', bins = 30) +
  geom_density(color = 'black', linewidth = 1) +
  labs(title = 'Histogram of Petrol Price',
       x = 'Petrol Price',
       y = 'Frequency') +
  theme_minimal()

#Create a Scatterplot (basics notes)
# x <-seatbelt$front
#y <-seatbelt$rear
#par(las=1, mar=c(4, 4, 5, 4))
#plot.new()
#plot.window(xlim=c(400,1400), ylim=c(200, 700))
#points(x, y, pch=5, cex=0.5)
#par(col="black", fg="black", col.axis="black")
#axis(1, at=seq(400, 1400, 300))
#axis(2, at=seq(200,700,100))
##plotting a box on just 2 axes
#box(bty="L")
#mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
#mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
#mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
#par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

#Scatterplot ggplot2
x <-seatbelt$front
y <-seatbelt$rear
ggplot(data = data.frame(x = x, y = y), aes(x = x, y = y)) +
  geom_point(shape = 24, size = 3, fill = "mediumpurple3") +
  xlim(400, 1400) +
  ylim(200, 700) +
  labs(title = "Comparing Seatbelt Related Incidences",
       x = "Front Related Incidences",
       y = "Rear Related Incidences") +
  theme_minimal() 



#HorizontalBarChart
seatbelt$decade <- 10 * (seatbelt$Year %/% 10)
fatalitiesbydecade <- table(seatbelt$decade)
ggplot(data = data.frame(decade = as.factor(names(fatalitiesbydecade)),
                         deaths = as.numeric(fatalitiesbydecade)), 
       aes(x = decade, y = deaths, fill = decade)) +
  geom_bar(stat = "identity") +
  labs(title = "Deaths by Decade",
       x = "Decade",
       y = "Number of Deaths") +
  theme_minimal() +
  scale_fill_manual(values = c("darkolivegreen4", "darkolivegreen2", "darkolivegreen4")) +
  coord_flip()




#VerticalBarChart

deaths_by_year <- tapply(seatbelt$DriversKilled, seatbelt$Year, sum)
deaths_by_year_df <- data.frame(Year = as.numeric(names(deaths_by_year)),
                                TotalDeaths = as.numeric(deaths_by_year))

ggplot(data = deaths_by_year_df, aes(x = factor(Year), y = TotalDeaths, fill = factor(Year))) +
  geom_bar(stat = "identity") +
  labs(title = "Total Deaths by Year",
       x = "Year",
       y = "Total Deaths") +
  theme_minimal() +
  scale_fill_manual(values = c("darkolivegreen4", "darkolivegreen4", "darkolivegreen4", "darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4","darkolivegreen4")) +
  ylim(0, max(deaths_by_year) + 20)





#BoxPlot boxplot(seatbelt$DriversKilled,
# main = "Boxplot of Drivers Killed",
# ylab = "Deaths",
#col = "darkorange3",
# border = "black")

ggplot(data = data.frame(DriversKilled = seatbelt$DriversKilled), 
       aes(y = DriversKilled)) +
  geom_boxplot(color = "black", fill = "darkorange3") +
  labs(title = "Boxplot of Drivers Killed",
       ylab = "Deaths") +
  theme_minimal()

#PieChart - mtcars 
#note to self - take note of which datsets are appropriate for different forms of graphs in the future

data(mtcars)

# Create a pie chart showing the distribution of cylinder counts
data(mtcars)
View(mtcars)
cylinder_counts <- table(mtcars$cyl)

#Data Frame
pie_data <- data.frame(
  cylinder = factor(names(cylinder_counts), levels = names(cylinder_counts)),
  count = as.numeric(cylinder_counts)
)

# Calculate percentages for the labels
pie_data$percent <- pie_data$count / sum(pie_data$count) * 100
pie_data$label <- paste0(pie_data$cylinder, "\n", round(pie_data$percent, 1), "%")

#actual plot
ggplot(data = pie_data, aes(x = "", y = percent, fill = cylinder)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y") +
  theme_void() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14),
    legend.position = "none"
  ) +
  ggtitle("How Many Cylinders?") +
  geom_text(aes(label = label), position = position_stack(vjust = 0.5))

```

**Exporting Charts**

```{r}
data(Seatbelts)
seatbelt <- data.frame (Year=floor(time(Seatbelts)) ,
Month=factor(cycle(Seatbelts) ,
labels=month.abb) , Seatbelts)
x <-seatbelt$front
y <-seatbelt$rear
par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

#Examples
#pdf(“rplot.pdf”): pdf file
#png(“rplot.png”): png file
#jpeg(“rplot.jpg”): jpeg file
#postscript(“rplot.ps”): postscript file
#bmp(“rplot.bmp”): bmp file
#win.metafile(“rplot.wmf”): windows metafile

#png
png("scatterplot.png")

par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

dev.off()

#jpg
png("scatterplot.jpg")

par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

dev.off()

#svg
png("scatterplot.svg")

par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

dev.off()

#tiff
png("scatterplot.tiff")

par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

dev.off()

#bmg
png("scatterplot.bmg")

par(las=1, mar=c(4, 4, 5, 4))
plot.new()
plot.window(xlim=c(400,1400), ylim=c(200, 700))
points(x, y, pch=5, cex=0.5)
par(col="black", fg="black", col.axis="black")
axis(1, at=seq(400, 1400, 300))
axis(2, at=seq(200,700,100))
#plotting a box on just 2 axes
box(bty="L")
mtext("Front Related Incidences", side=1, line=3, cex=0.8)
#las 0 means sideways label
mtext("Rear Related Incidences", side=2, line=3, las=0, cex=0.8)
mtext("Comparing Seatbelt Related Incidences", side=3, line=3,cex=1)
par(mar=c(3, 3, 2, 3), col="black", fg="black", col.axis="black")

dev.off()

#notes - PNG has the highest quality, whereas jpg and tiff have lower qualities. We cannot access the svg and bmg as presented with full graphics.


```
